import{LEGAL_DISCLAIMER,orderSourcesForDisplay,retrieve,ruleBasedAnswer,sourcesFooter}from"./search.js";
export async function answerQuestion(env,question,filters={}){
  const otherSectorLabel=filters.otherSectorLabel?String(filters.otherSectorLabel).trim().slice(0,80):"";
  const sources=await retrieve(env,question,filters,12),displaySources=orderSourcesForDisplay(sources);
  if(!sources.length)return{answer:ruleBasedAnswer(question,[],otherSectorLabel),sources:[],mode:"documental"};
  const relevantSources=sources.filter(source=>source.termMatch>0);
  if(!relevantSources.length)return{answer:ruleBasedAnswer(question,[],otherSectorLabel),sources:displaySources,mode:"documental"};
  const context=relevantSources.map((source,index)=>`[${index+1}] ${source.title}\nTIPO: ${source.source_type||source.document_type||"NO CONSTA"}\nÓRGANO: ${source.court_level||"NO CONSTA"}\nESTADO: ${source.procedural_status||"SITUACIÓN PROCESAL NO VERIFICADA"}\nCRITERIO: ${source.current_rule_summary||source.criteria||source.summary||"NO CONSTA"}`).join("\n\n");
  const otherSectorInstruction=otherSectorLabel?`El usuario ha indicado que su sector es «${otherSectorLabel}», que no tiene convenio colectivo propio en esta biblioteca. Dilo expresamente al inicio de la RESPUESTA DIRECTA y responde solo con normativa laboral general (Estatuto de los Trabajadores u otra ley aplicable) y jurisprudencia general si consta en el CONTEXTO. Nunca atribuyas a ese sector un convenio de otro sector distinto.`:"";
  const system=`Responde como asistente jurídico-sindical documental español. Contesta directamente la consulta con una explicación clara y motivada; no empieces diciendo cuántos documentos hay ni describas el inventario. Solo puedes usar el CONTEXTO; no mezcles instituciones jurídicas distintas (por ejemplo, un permiso retribuido no es lo mismo que una excedencia, y una reducción de jornada no es lo mismo que una adaptación de jornada): si el CONTEXTO trata de una institución distinta a la preguntada, dilo así y no traslades sus cifras a la pregunta. ${otherSectorInstruction} Aplica esta jerarquía de fuentes: 1) Estatuto de los Trabajadores y demás normativa aplicable; 2) convenio colectivo del sector seleccionado; 3) guías y doctrina jurídico-sindical CGT; 4) sentencias y jurisprudencia vigente; 5) otros criterios administrativos. Principio de norma mínima y condición más beneficiosa: el convenio colectivo nunca puede fijar condiciones por debajo de lo que establece el Estatuto de los Trabajadores u otra norma legal; si el CONTEXTO incluye tanto el Estatuto como el convenio regulando el mismo supuesto con duraciones, cuantías o condiciones distintas, indica ambas cifras exactas y señala expresamente que se aplica la más favorable para la persona trabajadora, salvo que el propio CONTEXTO indique lo contrario. No inventes números, plazos, ECLI, ROJ, fechas, artículos, empresas, recursos ni estados que no figuren literalmente en el CONTEXTO. Si falta un dato escribe exactamente: "El dato no consta en la biblioteca." Nunca presentes REVOCADA, ANULADA, CASADA_TOTALMENTE o SUPERADA_DOCTRINALMENTE como criterio vigente. Estructura la respuesta exactamente en estas secciones, cada una con su título en mayúsculas: RESPUESTA DIRECTA, EXPLICACIÓN RAZONADA, BASE LEGAL O CONVENCIONAL, CRITERIO JURISPRUDENCIAL (indica "No consta jurisprudencia específica en la biblioteca" si no hay ninguna en el CONTEXTO), CONDICIONES, EXCEPCIONES O LÍMITES, APLICACIÓN PRÁCTICA, ADVERTENCIA (sobre información no encontrada o no verificada). No sustituyes asesoramiento profesional.`;
  try{if(!env.AI)throw new Error("AI_UNAVAILABLE");const result=await env.AI.run(env.AI_MODEL||"@cf/meta/llama-3.2-3b-instruct",{messages:[{role:"system",content:system},{role:"user",content:`PREGUNTA: ${question}\n\nCONTEXTO:\n${context}`}],temperature:.1,max_tokens:1300});const aiText=result.response||String(result);return{answer:`${aiText}\n\n${sourcesFooter(relevantSources)}\n\n${LEGAL_DISCLAIMER}`,sources:displaySources,mode:"ai"}}catch{return{answer:ruleBasedAnswer(question,relevantSources,otherSectorLabel),sources:displaySources,mode:"documental-fallback"}}
}
