import{LEGAL_DISCLAIMER,orderSourcesForDisplay,retrieve,ruleBasedAnswer,sourcesFooter}from"./search.js";
export async function answerQuestion(env,question,filters={}){
  const otherSectorLabel=filters.otherSectorLabel?String(filters.otherSectorLabel).trim().slice(0,80):"";
  const sources=await retrieve(env,question,filters,12),displaySources=orderSourcesForDisplay(sources);
  if(!sources.length)return{answer:ruleBasedAnswer(question,[],otherSectorLabel),sources:[],mode:"documental"};
  const relevantSources=sources.filter(source=>source.termMatch>0);
  if(!relevantSources.length)return{answer:ruleBasedAnswer(question,[],otherSectorLabel),sources:displaySources,mode:"documental"};
  const contextSources=relevantSources.slice(0,1);
  const context=contextSources.map((source,index)=>`[${index+1}] ${source.title}\nTIPO: ${source.source_type||source.document_type||"NO CONSTA"}\nÓRGANO: ${source.court_level||"NO CONSTA"}\nESTADO: ${source.procedural_status||"SITUACIÓN PROCESAL NO VERIFICADA"}\nCRITERIO: ${source.current_rule_summary||source.criteria||source.summary||"NO CONSTA"}`).join("\n\n");
  const otherSectorInstruction=otherSectorLabel?`El usuario ha indicado que su sector es «${otherSectorLabel}», que no tiene convenio colectivo propio en esta biblioteca. Dilo expresamente al inicio de la RESPUESTA DIRECTA y responde solo con normativa laboral general (Estatuto de los Trabajadores u otra ley aplicable) y jurisprudencia general si consta en el CONTEXTO. Nunca atribuyas a ese sector un convenio de otro sector distinto.`:"";
  const system=`Responde como asistente jurídico-sindical documental español. Contesta directamente la consulta con una explicación clara y motivada; no empieces diciendo cuántos documentos hay ni describas el inventario. Solo puedes usar el CONTEXTO; la fuente [1] es la más relevante para esta pregunta y debe ser la base principal de tu respuesta. En la sección BASE LEGAL O CONVENCIONAL, transcribe literalmente y entre comillas el fragmento exacto de la fuente [1] que responde a la pregunta, sin resumirlo ni parafrasearlo, para no perder ni cambiar ningún dato. Antes de redactar la RESPUESTA DIRECTA, lee ese fragmento completo y localiza TODOS los supuestos que menciona (presta especial atención a listas con "o", "u", "y" que unen varios casos distintos en la misma frase); la RESPUESTA DIRECTA debe ser coherente con la cita literal y no puede omitir ningún supuesto que la cita sí incluya. No mezcles instituciones jurídicas distintas (por ejemplo, un permiso retribuido no es lo mismo que un complemento de incapacidad temporal, y una excedencia no es lo mismo que un permiso): si una fuente del CONTEXTO trata de una institución distinta a la preguntada, ignórala y no traslades sus cifras a la pregunta; usa solo la fuente que trate exactamente del mismo concepto preguntado. Si la fuente [1] sí contiene el dato, no digas que no consta. ${otherSectorInstruction} Aplica esta jerarquía de fuentes: 1) Estatuto de los Trabajadores y demás normativa aplicable; 2) convenio colectivo del sector seleccionado; 3) guías y doctrina jurídico-sindical CGT; 4) sentencias y jurisprudencia vigente; 5) otros criterios administrativos. No inventes números, plazos, ECLI, ROJ, fechas, artículos, empresas, recursos ni estados que no figuren literalmente en el CONTEXTO. Si ninguna fuente del CONTEXTO trata el concepto exacto preguntado, escribe exactamente: "El dato no consta en la biblioteca." Nunca presentes REVOCADA, ANULADA, CASADA_TOTALMENTE o SUPERADA_DOCTRINALMENTE como criterio vigente. Estructura la respuesta exactamente en estas secciones, cada una con su título en mayúsculas: RESPUESTA DIRECTA, EXPLICACIÓN RAZONADA, BASE LEGAL O CONVENCIONAL, CRITERIO JURISPRUDENCIAL (indica "No consta jurisprudencia específica en la biblioteca" si no hay ninguna en el CONTEXTO), CONDICIONES, EXCEPCIONES O LÍMITES, APLICACIÓN PRÁCTICA, ADVERTENCIA (sobre información no encontrada o no verificada). No sustituyes asesoramiento profesional.`;
  try{if(!env.AI)throw new Error("AI_UNAVAILABLE");const result=await env.AI.run(env.AI_MODEL||"@cf/meta/llama-3.2-3b-instruct",{messages:[{role:"system",content:system},{role:"user",content:`PREGUNTA: ${question}\n\nCONTEXTO:\n${context}`}],temperature:.1,max_tokens:1300});const aiText=result.response||String(result);return{answer:`${aiText}\n\n${sourcesFooter(contextSources)}\n\n${LEGAL_DISCLAIMER}`,sources:displaySources,mode:"ai"}}catch{return{answer:ruleBasedAnswer(question,contextSources,otherSectorLabel),sources:displaySources,mode:"documental-fallback"}}
}
