const encoder=new TextEncoder();
const bytesToHex=value=>[...new Uint8Array(value)].map(v=>v.toString(16).padStart(2,"0")).join("");
export async function digestHex(value){const bytes=value instanceof ArrayBuffer?value:typeof value==="string"?encoder.encode(value):value;const hash=await crypto.subtle.digest("SHA-256",bytes);return bytesToHex(hash)}
function constantTimeEqual(a,b){if(a.length!==b.length)return false;let diff=0;for(let i=0;i<a.length;i++)diff|=a.charCodeAt(i)^b.charCodeAt(i);return diff===0}
export async function verifyPassword(password,encoded){if(!encoded)return false;const [iterationsText,saltHex,expected]=encoded.split(":");const iterations=Number(iterationsText);if(!iterations||!saltHex||!expected)return false;const salt=Uint8Array.from(saltHex.match(/.{2}/g)||[],b=>parseInt(b,16));const key=await crypto.subtle.importKey("raw",encoder.encode(password),"PBKDF2",false,["deriveBits"]);const bits=await crypto.subtle.deriveBits({name:"PBKDF2",hash:"SHA-256",salt,iterations},key,256);return constantTimeEqual(bytesToHex(bits),expected)}
export async function hashPassword(password,iterations=310000){const salt=crypto.getRandomValues(new Uint8Array(16));const key=await crypto.subtle.importKey("raw",encoder.encode(password),"PBKDF2",false,["deriveBits"]);const bits=await crypto.subtle.deriveBits({name:"PBKDF2",hash:"SHA-256",salt,iterations},key,256);return`${iterations}:${bytesToHex(salt)}:${bytesToHex(bits)}`}
export function randomToken(){const bytes=crypto.getRandomValues(new Uint8Array(32));return [...bytes].map(v=>v.toString(16).padStart(2,"0")).join("")}
export function safeFilename(name){return String(name||"documento").normalize("NFKC").replace(/[^a-zA-Z0-9._-]+/g,"_").replace(/^\.+/,"").slice(0,120)||"documento"}
export function detectFile(bytes,mime,name){const head=new TextDecoder().decode(bytes.slice(0,5));const pdf=head==="%PDF-"&&mime==="application/pdf"&&/\.pdf$/i.test(name);const zip=bytes[0]===0x50&&bytes[1]===0x4b&&[0x03,0x05,0x07].includes(bytes[2])&&/\.zip$/i.test(name);return pdf?"pdf":zip?"zip":null}
export async function rateLimit(env,key,limit=30,windowSeconds=60){const bucket=Math.floor(Date.now()/1000/windowSeconds);const id=`${key}:${bucket}`;await env.DB.prepare("INSERT INTO rate_limits(id,count,expires_at) VALUES(?,1,?) ON CONFLICT(id) DO UPDATE SET count=count+1").bind(id,(bucket+1)*windowSeconds).run();const row=await env.DB.prepare("SELECT count FROM rate_limits WHERE id=?").bind(id).first();return Number(row?.count||0)<=limit}
