import{hashPassword}from"./security.js";
import{error,json}from"./http.js";
const ROLES=new Set(["admin","editor","consultante"]);
const SECTORS=new Set(["contact-center","laboral-general","servicios","construccion-metal-industria","comercio-finanzas-seguros","social-dependencia-ensenanza","hosteleria-turismo-alimentacion"]);
export const isAdmin=user=>user?.role==="admin";
export const canUpload=user=>user?.role==="admin"||user?.role==="editor";
export const canAccessTelemarketing=user=>user?.role==="admin"||Boolean(user?.telemarketing_access);
export function validateNewUser(input){const username=String(input.username||"").trim();const password=String(input.password||"");const role=ROLES.has(input.role)?input.role:"consultante";const sectorRaw=String(input.sector||"").trim();const sector=SECTORS.has(sectorRaw)?sectorRaw:null;const telemarketingAccess=input.telemarketing_access?1:0;if(!/^[\p{L}\p{N}._-]{3,50}$/u.test(username))return{error:"El usuario debe tener entre 3 y 50 caracteres y no contener espacios."};if(password.length<8||password.length>128)return{error:"La contraseña temporal debe tener entre 8 y 128 caracteres."};return{username,password,role,sector,telemarketingAccess}}
export async function listUsers(env,headers){const{results}=await env.DB.prepare("SELECT id,username,role,sector,telemarketing_access,active,created_at FROM users ORDER BY username").all();return json({users:results},200,headers)}
export async function createUser(request,env,headers,actor){const input=validateNewUser(await request.json());if(input.error)return error(input.error,400,headers);if(input.username.toLowerCase()===String(env.ADMIN_USER||"").toLowerCase())return error("Ese nombre está reservado para la administración principal.",409,headers);const existing=await env.DB.prepare("SELECT id FROM users WHERE lower(username)=lower(?)").bind(input.username).first();if(existing)return error("El nombre de usuario ya existe.",409,headers);const hash=await hashPassword(input.password);const result=await env.DB.prepare("INSERT INTO users(username,password_hash,role,sector,telemarketing_access,active,created_by,updated_at) VALUES(?,?,?,?,?,1,?,CURRENT_TIMESTAMP)").bind(input.username,hash,input.role,input.sector,input.telemarketingAccess,actor.username).run();await env.DB.prepare("INSERT INTO audit_log(actor,action,entity_type,entity_id,details_json) VALUES(?,?,?,?,?)").bind(actor.username,"CREATE_USER","user",String(result.meta?.last_row_id||input.username),JSON.stringify({username:input.username,role:input.role,sector:input.sector,telemarketing_access:input.telemarketingAccess})).run();return json({id:result.meta?.last_row_id,username:input.username,role:input.role,sector:input.sector,telemarketing_access:input.telemarketingAccess},201,headers)}
